version "4.10.0"

// Vanilla Loadout Codes
const LEGACY_HDLD_355BOX            = "3bx";
const LEGACY_HDLD_4MMBOX            = "4bx";
const LEGACY_HDLD_7MMBOX            = "abx";
const LEGACY_HDLD_9MMBOX            = "9bx";
const LEGACY_HDLD_RKTBOX            = "rbx";
const LEGACY_HDLD_SHELLBOX          = "sbx";

// HDBulletLib Loadout Codes
const LEGACY_HDLD_4GSLUGBOX         = "gbx";
const LEGACY_HDLD_500HBOX           = "hbx";
const LEGACY_HDLD_500LBOX           = "lbx";
const LEGACY_HDLD_5MMBOX            = "bbx";
const LEGACY_HDLD_45ACPBOX          = "pbx";
const LEGACY_HDLD_45LCBOX           = "cbx";
const LEGACY_HDLD_50AEBOX           = "ebx";
const LEGACY_HDLD_50AMBOX           = "tbx";
const LEGACY_HDLD_6MMFLECHETTEBOX   = "6bx";
const LEGACY_HDLD_10MMBOX           = "0bx";
const LEGACY_HDLD_3006BOX           = "mbx";
const LEGACY_HDLD_50OMGBOX          = "obx";
const LEGACY_HDLD_SLUGBOX           = "ubx";
const LEGACY_HDLD_EXPLOSIVESHELLBOX = "xbx";

// Base Class
#include "zscript/legacyAmmoBox.zs"

// Vanilla Ammoboxes
#include "zscript/Vanilla/9mmBox.zs"
#include "zscript/Vanilla/shellBox.zs"
#include "zscript/Vanilla/7mmBox.zs"
#include "zscript/Vanilla/355Box.zs"
#include "zscript/Vanilla/rocketBox.zs"

// HDBulletLib Ammoboxes
#include "zscript/HDBulletLib/4GaSlugBox.zs"
#include "zscript/HDBulletLib/500HeavyBox.zs"
#include "zscript/HDBulletLib/500LightBox.zs"
#include "zscript/HDBulletLib/5mmBox.zs"
#include "zscript/HDBulletLib/45ACPBox.zs"
#include "zscript/HDBulletLib/45LCBox.zs"
#include "zscript/HDBulletLib/50AEBox.zs"
#include "zscript/HDBulletLib/50AMBox.zs"
#include "zscript/HDBulletLib/6mmBox.zs"
#include "zscript/HDBulletLib/10mmBox.zs"
#include "zscript/HDBulletLib/3006Box.zs"
#include "zscript/HDBulletLib/50OMGBox.zs"
#include "zscript/HDBulletLib/slugBox.zs"
#include "zscript/HDBulletLib/explosiveShellBox.zs"