name: Build PK3
description: Builds the PK3
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - uses: montudor/action-zip@v1
    with:
      args: zip -r "reusable-ammoboxes-${{ env.SUFFIX }}.pk3" . -i sprites/* zscript/* CHANGELOG.md LANGUAGE.* LICENSE MAPINFO README.md SNDINFO zscript.zs
